# Generated by Django 2.0 on 2018-01-18 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Blog Entry Title')),
                ('text', models.CharField(max_length=20000, verbose_name='blog entry text')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
